<a href="https://colab.research.google.com/github/Preet1990/Decision-Trees/blob/main/Bagging_and_Boosting_ensemble_project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline
import numpy as np
import pandas as pd
from matplotlib import pyplot as pyplot
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from scipy.stats import zscore

In [ ]:
df = pd.read_csv('/content/talking_data.csv')
df.head()

ip  app  device  os  channel           click_time attributed_time  \
0   87540   12       1  13      497  2017-11-07 09:30:38             NaN   
1  105560   25       1  17      259  2017-11-07 13:40:27             NaN   
2  101424   12       1  19      212  2017-11-07 18:05:24             NaN   
3   94584   13       1  13      477  2017-11-07 04:58:08             NaN   
4   68413   12       1   1      178  2017-11-09 09:00:09             NaN   

   is_attributed  
0              0  
1              0  
2              0  
3              0  
4              0

**1. Explore the dataset for anomalies and missing values and take corrective actions if necessary.**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype 
---  ------           --------------   ----- 
 0   ip               100000 non-null  int64 
 1   app              100000 non-null  int64 
 2   device           100000 non-null  int64 
 3   os               100000 non-null  int64 
 4   channel          100000 non-null  int64 
 5   click_time       100000 non-null  object
 6   attributed_time  227 non-null     object
 7   is_attributed    100000 non-null  int64 
dtypes: int64(6), object(2)
memory usage: 6.1+ MB


In [ ]:
df['is_attributed'].value_counts()

0    99773
1      227
Name: is_attributed, dtype: int64

In [ ]:
df.describe()

ip           app         device             os  \
count  100000.000000  100000.00000  100000.000000  100000.000000   
mean    91255.879670      12.04788      21.771250      22.818280   
std     69835.553661      14.94150     259.667767      55.943136   
min         9.000000       1.00000       0.000000       0.000000   
25%     40552.000000       3.00000       1.000000      13.000000   
50%     79827.000000      12.00000       1.000000      18.000000   
75%    118252.000000      15.00000       1.000000      19.000000   
max    364757.000000     551.00000    3867.000000     866.000000   

             channel  is_attributed  
count  100000.000000  100000.000000  
mean      268.832460       0.002270  
std       129.724248       0.047591  
min         3.000000       0.000000  
25%       145.000000       0.000000  
50%       258.000000       0.000000  
75%       379.000000       0.000000  
max       498.000000       1.000000

In [ ]:
df.shape

(100000, 8)

In [ ]:
df.isnull().values.any()

True

In [ ]:
miss_val = df.isna().sum()
miss_val

ip                     0
app                    0
device                 0
os                     0
channel                0
click_time             0
attributed_time    99773
is_attributed          0
dtype: int64

In [ ]:
df["attributed_time"].fillna("NaN", inplace= True) # fix null values
df.isnull().values.any()

False

**2. Which column has maximum number of unique values present among all the available columns**

In [ ]:
print(df.nunique())

# click_time column has maximum number of unique values i.e  80350

ip                 34857
app                  161
device               100
os                   130
channel              161
click_time         80350
attributed_time      228
is_attributed          2
dtype: int64


**3. Use an appropriate technique to get rid of all the apps that are very rare (say which comprise of less                than 20% clicks) and plot the rest..** 

**4. By using Pandas derive new features such as - 'day_of_week' , 'day_of_year' , 'month' , and 'hour' as                  float/int datatypes using the 'click_time' column . Add the newly derived columns in original dataset.**

In [ ]:
# from datetime import datetime

# df['click_time'] = pd.to_datetime(df['click_time'])
# df.dtypes

In [ ]:
# df['day_of_year'] = pd.DatetimeIndex(df['click_time']).year
# df['month'] = pd.DatetimeIndex(df['click_time']).month
# df['day_of week'] = pd.DatetimeIndex(df['click_time']).day
# df['hour'] = pd.DatetimeIndex(df['click_time']).time

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype 
---  ------           --------------   ----- 
 0   ip               100000 non-null  int64 
 1   app              100000 non-null  int64 
 2   device           100000 non-null  int64 
 3   os               100000 non-null  int64 
 4   channel          100000 non-null  int64 
 5   click_time       100000 non-null  object
 6   attributed_time  100000 non-null  object
 7   is_attributed    100000 non-null  int64 
dtypes: int64(6), object(2)
memory usage: 6.1+ MB


In [ ]:
df

ip  app  device  os  channel           click_time attributed_time  \
0       87540   12       1  13      497  2017-11-07 09:30:38             NaN   
1      105560   25       1  17      259  2017-11-07 13:40:27             NaN   
2      101424   12       1  19      212  2017-11-07 18:05:24             NaN   
3       94584   13       1  13      477  2017-11-07 04:58:08             NaN   
4       68413   12       1   1      178  2017-11-09 09:00:09             NaN   
...       ...  ...     ...  ..      ...                  ...             ...   
99995  124883   11       1  19      122  2017-11-09 13:25:41             NaN   
99996   85150    9       1  13      244  2017-11-07 11:25:43             NaN   
99997   18839    3       1  13       19  2017-11-08 11:38:42             NaN   
99998  114276   15       1  12      245  2017-11-08 17:55:21             NaN   
99999  119349   14       1  15      401  2017-11-07 14:32:27             NaN   

       is_attributed  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  
...              ...  
99995              0  
99996              0  
99997              0  
99998              0  
99999              0  

[100000 rows x 8 columns]

In [ ]:

for feature in df.columns:
  if df[feature].dtype == 'object':
    df[feature] = pd.Categorical(df[feature]).codes

df.info()   

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ip               100000 non-null  int64
 1   app              100000 non-null  int64
 2   device           100000 non-null  int64
 3   os               100000 non-null  int64
 4   channel          100000 non-null  int64
 5   click_time       100000 non-null  int32
 6   attributed_time  100000 non-null  int16
 7   is_attributed    100000 non-null  int64
dtypes: int16(1), int32(1), int64(6)
memory usage: 5.1 MB


**5. Divide the data into training and testing subsets into 80:20 ratio(Train_data = 80% , Testing_data = 20%) and
     check the average download rates('is_attributed') for train and test data, scores should be comparable.**

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import preprocessing

In [ ]:
x = df.drop(['click_time','is_attributed','attributed_time'], axis=1)
y = df['is_attributed']

# Split X and y into training and test set in 80:20 ratio

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=10)

In [ ]:
y.value_counts()

0    99773
1      227
Name: is_attributed, dtype: int64

**6. Apply XGBoostClassifier with default parameters on training data and make first 10 prediction for Test data.          NOTE: Use y_pred = model.predict_proba(X_test) since we need probabilities to compute AUC.** 

In [ ]:
from xgboost import XGBClassifier # XGB stands for Extreme Gradient Boosting
xgbcl = XGBClassifier()
xgbcl = xgbcl.fit(x_train, y_train)
y_pred = xgbcl.predict(x_test)
y_pred_pro  = xgbcl.predict_proba(x_test)
xgbcl_score=xgbcl.score(x_test , y_test)
print("The Extreme Gradient Boost Classifier model accuracy is {}".format(xgbcl_score))
print(" ")
print(y_test,y_pred )

The Extreme Gradient Boost Classifier model accuracy is 0.9982
 
33226    0
64804    0
39763    0
51270    0
9698     0
        ..
84466    0
39137    0
3153     0
80052    0
98698    0
Name: is_attributed, Length: 20000, dtype: int64 [0 0 0 ... 0 0 0]


In [ ]:
print(metrics.classification_report(y_test,y_pred))
metrics.confusion_matrix(y_test,y_pred)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19961
           1       0.71      0.13      0.22        39

    accuracy                           1.00     20000
   macro avg       0.86      0.56      0.61     20000
weighted avg       1.00      1.00      1.00     20000



array([[19959,     2],
       [   34,     5]])

In [ ]:
# Use SMOTE to balance the embalanced data

from imblearn.over_sampling import SMOTE
smote = SMOTE()

x_train_smote,y_train_smote = smote.fit_resample(x_train.astype('float'),y_train)


from collections import Counter
print("Before SMOTE :" , Counter(y_train))
print("After SMOTE :" , Counter(y_train_smote))
print("  ")
xgbcl = xgbcl.fit(x_train_smote, y_train_smote)
y_pred = xgbcl.predict(x_test)
print(metrics.classification_report(y_test,y_pred))
metrics.confusion_matrix(y_test,y_pred)

Before SMOTE : Counter({0: 79812, 1: 188})
After SMOTE : Counter({0: 79812, 1: 79812})
  
              precision    recall  f1-score   support

           0       1.00      0.97      0.98     19961
           1       0.05      0.90      0.10        39

    accuracy                           0.97     20000
   macro avg       0.53      0.93      0.54     20000
weighted avg       1.00      0.97      0.98     20000



array([[19347,   614],
       [    4,    35]])

**7. On evaluating the predictions made by the model what is the AUC/ROC score with default hyperparameters.**

In [ ]:
from sklearn import metrics

#calculate AUC of model
auc_xgbcl = metrics.roc_auc_score(y_test, y_pred)
print(auc_xgbcl)

0.933337957735533


**8. Compute feature importance score and name the top 5 features/columns .**

In [ ]:
skip it

**9. Apply BaggingClassifier with base_estimator LogisticRegression and compute AUC/ROC score.**

In [ ]:
from sklearn.ensemble import BaggingClassifier

bgcl = BaggingClassifier(n_estimators=10)


bgcl = bgcl.fit(x_train_smote,y_train_smote)
y_pred1 = bgcl.predict(x_test)
bgcl_score=bgcl.score(x_test, y_test)
print("The Bagging classifier model accuracy is {}".format(bgcl_score))
print(metrics.classification_report(y_test,y_pred1))
print("The confusion matrix of Bagging classifier model is")
print(metrics.confusion_matrix(y_test,y_pred1))

The Bagging classifier model accuracy is 0.99625
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     19961
           1       0.24      0.44      0.31        39

    accuracy                           1.00     20000
   macro avg       0.62      0.72      0.66     20000
weighted avg       1.00      1.00      1.00     20000

The confusion matrix of Bagging classifier model is
[[19908    53]
 [   22    17]]


In [ ]:
auc_bgcl = metrics.roc_auc_score(y_test, y_pred1)
print(auc_bgcl)

0.7166211291505615


**10.  On the basis of AUC/ROC score which one will you choose from BaggingClassifier and XGBoostClassifier and              why?What does AUC/ROC score signifies?**

In [ ]:
print("XGBClassifier AUC :" , auc_xgbcl )
print("XGBClassifier AUC :" , auc_bgcl )
print(" ")
print("On the basis of AUC/ROC score we choose XGBoostClassifier as XGBoosting is tries to reduce bias.")


XGBClassifier AUC : 0.933337957735533
XGBClassifier AUC : 0.7166211291505615
 
On the basis of AUC/ROC score we choose XGBoostClassifier as XGBoosting is tries to reduce bias.


**11.  What is the accuracy for BaggingClassifier and XGBoostClassifier?()**

In [ ]:
print("The Extreme Gradient Boost Classifier model accuracy is {}".format(xgbcl_score))
print(" ")
print("The Bagging classifier model accuracy is {}".format(bgcl_score))

The Extreme Gradient Boost Classifier model accuracy is 0.9982
 
The Bagging classifier model accuracy is 0.99625
